version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@umijs/test"
    versions:
    - 3.3.10
    - 3.3.11
    - 3.3.7
    - 3.3.9
    - 3.4.0
    - 3.4.1
    - 3.4.10
    - 3.4.11
    - 3.4.13
    - 3.4.2
    - 3.4.3
    - 3.4.4
    - 3.4.6
    - 3.4.7
    - 3.4.8
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: "@umijs/preset-react"
    versions:
    - 1.7.13
    - 1.8.0
    - 1.8.1
    - 1.8.2
    - 1.8.3
    - 1.8.4
